---
name: setup-kubeconfig-for-eks
description: |
  This helper sets up kubeconfig for an Amazon EKS cluster.
  It uses the AWS CLI to update the kubeconfig file with the necessary configuration to connect to the EKS cluster.
args:
  - name: cluster_name
    description: Name of the Amazon EKS cluster
    required: true
  - name: cluster_region
    description: AWS region where the EKS cluster is located
    default: "us-west-2"
requirements:
  platforms:
    - os: linux
    - os: darwin

steps:
  - name: update-kubeconfig
    description: "Update kubeconfig for the EKS cluster."
    inline: |
      aws eks update-kubeconfig --region {{ .Args.cluster_region }} --name {{ .Args.cluster_name }}
      if [ "$?" -ne 0 ]; then
        echo "Failed to update kubeconfig for EKS cluster" >&2
        exit 1
      fi
      echo "Kubeconfig updated successfully for EKS cluster: {{ .Args.cluster_name }}"
